// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYNGeto46GhPAnPDrGdKqXaR7B6Z8LXW0',
    appId: '1:450974042448:web:e54da66219f24b0db2c455',
    messagingSenderId: '450974042448',
    projectId: 'quotify-89cab',
    authDomain: 'quotify-89cab.firebaseapp.com',
    storageBucket: 'quotify-89cab.appspot.com',
    measurementId: 'G-1PRXBXWHRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcNjMCaeKSmnC1Fbhqd17YITe1H9pm9Tg',
    appId: '1:450974042448:android:7d14fab6bae1b0f1b2c455',
    messagingSenderId: '450974042448',
    projectId: 'quotify-89cab',
    storageBucket: 'quotify-89cab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYgNgw3jx_GSeJIL56OynMW_w2zRpPEQw',
    appId: '1:450974042448:ios:09d3f5204dba5606b2c455',
    messagingSenderId: '450974042448',
    projectId: 'quotify-89cab',
    storageBucket: 'quotify-89cab.appspot.com',
    androidClientId: '450974042448-iltoqsddjgg21duc9ca6ps5uma37s2hk.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYgNgw3jx_GSeJIL56OynMW_w2zRpPEQw',
    appId: '1:450974042448:ios:09d3f5204dba5606b2c455',
    messagingSenderId: '450974042448',
    projectId: 'quotify-89cab',
    storageBucket: 'quotify-89cab.appspot.com',
    androidClientId: '450974042448-iltoqsddjgg21duc9ca6ps5uma37s2hk.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq1v3yjVPT-ICeVPD8_n41WoWF-uuYrWU',
    appId: '1:450974042448:web:02f0cfbc4548634db2c455',
    messagingSenderId: '450974042448',
    projectId: 'quotify-89cab',
    authDomain: 'quotify-89cab.firebaseapp.com',
    storageBucket: 'quotify-89cab.appspot.com',
    measurementId: 'G-ZXW2YS9L2R',
  );

}